export const roasts = [
  "{name} talks like expired pizza 😂",
  "{name} is sweating already 👀",
  "{name} sounds suspicious 🤨",
  "{name} is acting too innocent 💀",
  "{name} almost exposed themselves 😂",
  "{name} forgot their own lie 🤣",
  "{name} is talking too fast 🏃",
  "{name} blinked too much 👁️",
  "{name} sounds like a fake detective 🕵️",
  "{name} definitely practiced this speech 😂",
  "{name} is nervous for no reason 😏",
  "{name} almost cried explaining the word 😭",
  "{name} sounds downloaded from Google 🤖",
  "{name} is cooking nonsense 🍳",
  "{name} forgot what game this is 🎮",
  "{name} is trying too hard 😭",
  "{name} looks guilty already 🚨",
  "{name} speaks like a cartoon villain 😈",
  "{name} just exposed their village people 😂",
  "{name} sounds like AI with low battery 🔋",
  "{name} is confusing everybody 😵",
  "{name} needs acting lessons 🎭",
  "{name} is giving impostor energy ⚡",
  "{name} talks like they know nothing 🤡",
  "{name} almost snitched on themselves 🤭",
  "{name} sounds too calm 😳",
  "{name} is overexplaining everything 📚",
  "{name} is moving suspiciously 🚶",
  "{name} sounds like a criminal lawyer ⚖️",
  "{name} definitely Googled the answer 😂",
  "{name} is trying to survive at all cost 💀",
  "{name} forgot to breathe while talking 😭",
  "{name} sounds like a confused teacher 🍎",
  "{name} is sweating through the phone 📱",
  "{name} is fighting for their life 😂",
  "{name} sounds like a fake prophet 🔮",
  "{name} is talking in circles 🔄",
  "{name} sounds like they just woke up 😴",
  "{name} is acting like an NPC 🎮",
  "{name} sounds more fake than monopoly money 💵",
  "{name} talks like a scammer 📞",
  "{name} forgot the assignment 📄",
  "{name} is giving red flags 🚩",
  "{name} sounds like they copied homework ✍️",
  "{name} talks like a tired robot 🤖",
  "{name} almost confessed accidentally 😂",
  "{name} is too quiet 👂",
  "{name} sounds like a backup singer 🎤",
  "{name} is defending themselves too much 🛡️",
  "{name} just entered panic mode 🚨",
  "{name} sounds like a fake witness 👀",
  "{name} looks guilty in 4K 📺",
  "{name} is speaking pure grammar without sense 📖",
  "{name} is buffering mentally 🧠",
  "{name} sounds like they are making it up live 🎬",
  "{name} just unlocked suspicious mode 🔓",
  "{name} talks like a broken GPS 🗺️",
  "{name} sounds like they watched too many crime movies 🎥",
  "{name} is trying not to laugh 😂",
  "{name} sounds too rehearsed 🎭",
  "{name} is moving like a secret agent 🕶️",
  "{name} talks like a confused uncle 😂",
  "{name} forgot the word completely 🫠",
  "{name} sounds like fake WiFi 📶",
  "{name} is surviving by luck 🍀",
  "{name} sounds like a random generator 🎰",
  "{name} is hiding something 👀",
  "{name} just said absolutely nothing 😭",
  "{name} is acting innocent but we know 🤨",
  "{name} talks like a villain in episode 1 📺",
  "{name} sounds like expired internet 🌐",
  "{name} is suspiciously confident 😎",
  "{name} sounds like they are lying professionally 💼",
  "{name} forgot how humans talk 😂",
  "{name} sounds like a fake tutorial 🎥",
  "{name} is panicking internally 😭",
  "{name} sounds like they need help 🆘",
  "{name} just confused themselves 🤯",
  "{name} sounds like they skipped rehearsal 🎤",
  "{name} talks like a malfunctioning robot 🤖",
  "{name} sounds too random 🎲",
  "{name} is acting like the main character 🎬",
  "{name} sounds like fake news 📰",
  "{name} forgot what reality is 🌍",
  "{name} is speaking premium nonsense 💎",
  "{name} sounds guilty beyond repair 🔧",
  "{name} is fighting invisible demons 😂",
  "{name} talks like a sleepy lecturer 💤",
  "{name} sounds like they lost the plot 📖",
  "{name} is suspiciously dramatic 🎭",
  "{name} sounds like corrupted audio 🎧",
  "{name} is giving chaos energy 🌪️",
  "{name} talks like a movie trailer 🎬",
  "{name} sounds like they need a restart 🔄",
  "{name} is sweating in HD 📹",
  "{name} forgot how this game works 🎮",
  "{name} sounds like fake confidence 😅",
  "{name} is acting too smooth 😏",
  "{name} sounds like a confused tourist 🧳",
  "{name} is one sentence away from exposure 🚨",
  "{name} sounds like mystery flavor chips 🍟",
  "{name} is talking but saying nothing 😂",
  "{name} sounds suspiciously peaceful ☮️",
  "{name} is giving criminal mastermind vibes 🧠",
];

export const praises = [
  "{name} fooled everybody 😎",
  "{name} deserves an Oscar 🎭",
  "{name} carried the round 🔥",
  "{name} is a mastermind 🧠",
  "{name} played perfectly 👑",
  "{name} outsmarted the whole lobby 😈",
  "{name} deserves MVP 🏆",
  "{name} is too smart for this game 🤯",
  "{name} played like a legend ⚡",
  "{name} just cooked everybody 🍳",
  "{name} survived like a champion 🥇",
  "{name} is dangerous at this game 😳",
  "{name} fooled even the host 😂",
  "{name} played with confidence 💪",
  "{name} deserves a trophy 🏅",
  "{name} just broke the game 🎮",
  "{name} is secretly a detective 🕵️",
  "{name} played smooth 😎",
  "{name} has elite skills 🚀",
  "{name} carried the discussion 🎤",
  "{name} played like a movie star 🌟",
  "{name} deserves applause 👏",
  "{name} just unlocked genius mode 🧠",
  "{name} survived pure pressure 😅",
  "{name} is too good 😭",
  "{name} deserves respect 💯",
  "{name} outplayed everyone 🎯",
  "{name} is impossible to read 👀",
  "{name} fooled the entire room 😂",
  "{name} is built for this game 🔥",
  "{name} deserves a crown 👑",
  "{name} is a strategic genius ♟️",
  "{name} just embarrassed the detectives 🤣",
  "{name} has elite acting skills 🎭",
  "{name} deserves a standing ovation 👏",
  "{name} played with style 😎",
  "{name} is carrying the server 🚀",
  "{name} is smarter than everybody today 🧠",
  "{name} survived like a boss 💼",
  "{name} just turned into Sherlock Holmes 🔍",
  "{name} fooled the smartest player 😂",
  "{name} is the king of impostors 👑",
  "{name} deserves unlimited points 💎",
  "{name} is built different ⚡",
  "{name} just dominated the round 🎮",
  "{name} is too clean with it 🧼",
  "{name} played flawlessly ✨",
  "{name} deserves hall of fame status 🏆",
  "{name} just became a legend 📖",
  "{name} is impossible to catch 🚔",
];